# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - main: ./cmd/mcbdd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats: ["tar.gz"] # Korrigiert: 'format' ist deprecated
    format_overrides:
      - goos: windows
        formats: ["zip"] # Korrigiert: 'format' ist deprecated

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next" # Korrigiert: 'name_template' ist deprecated

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

upx:
  - enabled: true
    goos: [linux]
    compress: best
    lzma: true

dockers:
  - dockerfile: Containerfile
    image_templates:
      # Wir nutzen 'tolower', um den Owner-Namen kleinzuschreiben
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/mailcow-birthday-daemon:{{ .Major }}"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/mailcow-birthday-daemon:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/mailcow-birthday-daemon:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/mailcow-birthday-daemon:latest"
